version: "3.9"
services:
  api:
    build: ./server
    env_file:
      - ./server/.env.example # replace with .env in prod
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  client:
    build: ./client
    ports:
      - "3000:80"
  mongo:
    image: mongo:7
    restart: always
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: